### ISSUE TITLE
Questions Related to Repo Files

### ISSUE THREAD

**Issue by CheeseL0ver** [Modman/SNES-Game-Genie-v1.0#1]
Hey Modman,

I happen to stumble across these repos while working on a reverse engineering project and I was curious about two things in particular. 

Firstly, you seem to supply the bins, and gerbers for the PCBs but no PCB design files themselves (i.e. the files you would open in KiCad. I am curious if you also have access to these raw files and if you would mind sharing them with the community as well. 

Second, I am curious if you know of/have BOM files for some of the other projects archived here (I am most interested in all Datel DS devices).

I am sorry to have made this an "issue" on Github, but I do not have other means of connecting you, if need be I am happy to communicate through other channels. 

Also allow me to thank you for the archival work you are doing! It is truly amazing and I am hoping to help by contributing additional documentation as I tinker around with what is available. 

-Cheers
Shandon

**Comment by RWeick** [comment]
Hi, yes I do have all of the Kicad files and I am willing to share them. I'll upload the ones for the DS devices shortly. I haven't made a standalone BOM, although everything is fully labeled in the schematics (ratings, measurements) and for any small components that don't have their package size identified, you could take a measurement of the pads in the PCB Kicad file to figure out what will fit there. Thanks for showing interest and I look forward to your contributions as well! It's certainly taken a lot of effort to put this together, but there's still plenty of work to be done to finish documenting these devices. Analyzing and replicating the behavior of the GALs and FPGAs, primarily, is what remains.

**Comment by CheeseL0ver** [comment]
Thank you for releasing the files. Are you creating all these designs be directly referencing the original devices? I have been trying to track down a few of them for VR research.
